name: React app deploy using Action on github
on:
  push:
    branches:
      - master

jobs: 
  build:
    name: Building
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Installing dependencies
        run: npm install
      - name: Building repo
        run: npm run build
      - name: Deploy to firebase  
        run: firebase deploy --token=${{secrets.FIREBASE_TOKEN}}
      


  